
#Область include_core_base_Helpers_ЛокализацияНазваниеПродукта
#КонецОбласти

#Область include_base_CommonModule_ИменаМодулейСервер
#КонецОбласти

#Область include_kedo_base_CommonModule_ПодключаемыеКоманды_Интеграция
#КонецОбласти
